# Generated by Django 4.0.6 on 2022-07-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_zap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zapatos',
            options={'ordering': ('-modelo', '-talla'), 'verbose_name': 'My Shoe', 'verbose_name_plural': 'My Shoes'},
        ),
        migrations.AddField(
            model_name='accesorios',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_zap.proveedores'),
        ),
        migrations.AlterUniqueTogether(
            name='zapatos',
            unique_together={('modelo', 'talla')},
        ),
    ]
